@file:OptIn(org.jetbrains.kotlin.gradle.ExperimentalWasmDsl::class)

plugins {
    id("org.jetbrains.kotlin.multiplatform")
    id("org.jetbrains.kotlin.plugin.compose")
    id("org.jetbrains.compose")
}

// The browser build: the scheduling core's own output, and beneath it the
// first real screen of the app -- :ui's OpponentsScreen over the browser
// database, both unmodified from what Android runs.
//
// The remaining screens follow. Keeping the entry point here rather than in
// :shared or :ui means both of those stay libraries, and the Android build
// never sees any of this.

// A version, a build type and a short hex commit will not contain a quote or
// a backslash, so this guards against a surprise rather than a plausible
// input -- but the surprise would otherwise surface as a compile error inside
// generated code, which is a miserable thing to read.
fun kotlinLiteral(value: String): String =
    "\"" + value.replace("\\", "\\\\").replace("\"", "\\\"") + "\""

// Whether a requested task is the dev server rather than the distribution.
fun String.isDevelopmentTaskName(): Boolean =
    !contains("Production", ignoreCase = true) &&
        (contains("Development", ignoreCase = true) || endsWith("BrowserRun"))

// What the About section reports about this build.
//
// There is no BuildConfig here -- that is generated per Android application
// module, and has no equivalent on the web -- so the equivalent is generated
// below, as a Kotlin source file the bundle compiles in. The version and the
// commit are read from outside this file (gradle.properties and the root
// build) precisely so that the browser and the APK cannot claim to be
// different versions of the same commit.
val appVersionName = providers.gradleProperty("appVersionName").get()
val appVersionCode = providers.gradleProperty("appVersionCode").get().toInt()
val headCommit = rootProject.extra["gitCommit"] as String

// Which of the two bundles this is.
//
// Both come out of one Kotlin compilation -- development and production
// differ in what webpack does with the output, not in what the compiler
// produced -- so nothing inside the compilation can distinguish them, and the
// answer has to be settled here, from what the build was asked to do. The
// Kotlin plugin's own task naming is the signal: anything *Development*, and
// a bare *BrowserRun*, is the dev server; everything else is the distribution
// that Pages publishes.
//
// -PwebBuildType= overrides it, for anyone driving the build another way.
val webBuildType: String = (findProperty("webBuildType") as String?)
    ?.trim()?.takeIf { it.isNotEmpty() }
    ?: if (gradle.startParameter.taskNames.any { it.isDevelopmentTaskName() }) "debug" else "release"

// Registered as a task, with the four values declared as inputs, so Gradle
// reruns it when the commit or the version changes and leaves the compilation
// alone when neither did.
val generateWebBuildInfo = tasks.register("generateWebBuildInfo") {
    description = "Generates the BuildInfo the browser build reports in About."

    val outputDir = layout.buildDirectory.dir("generated/buildInfo/wasmJsMain/kotlin")

    // Everything the action needs, resolved now: the task body has to hold
    // plain values rather than reach back into the project, or configuration
    // caching has nothing it can serialize.
    val versionCode = appVersionCode
    val versionNameLiteral = kotlinLiteral(appVersionName)
    val buildTypeLiteral = kotlinLiteral(webBuildType)
    val gitCommitLiteral = kotlinLiteral(headCommit)

    inputs.property("versionName", appVersionName)
    inputs.property("versionCode", appVersionCode)
    inputs.property("buildType", webBuildType)
    inputs.property("gitCommit", headCommit)
    outputs.dir(outputDir)

    doLast {
        val source = outputDir.get().asFile
            .resolve("com/fencing/spacedrepetition/web/GeneratedBuildInfo.kt")
        source.parentFile.mkdirs()
        source.writeText(
            """
            // SPDX-FileCopyrightText: 2026 Enmar Abrams
            // SPDX-License-Identifier: GPL-3.0-or-later

            // Generated by :web's generateWebBuildInfo task. Do not edit.

            package com.fencing.spacedrepetition.web

            import com.fencing.spacedrepetition.BuildInfo

            internal val GENERATED_BUILD_INFO: BuildInfo = BuildInfo(
                versionName = $versionNameLiteral,
                versionCode = $versionCode,
                buildType = $buildTypeLiteral,
                gitCommit = $gitCommitLiteral
            )

            """.trimIndent()
        )
    }
}

kotlin {
    jvmToolchain(17)

    wasmJs {
        outputModuleName.set("fencing-web")

        // :shared addresses the SQLite worker relative to import.meta.url,
        // and this is the module that actually gets bundled, so the format
        // has to be settled here too. index.html already loads the bundle
        // with type="module".
        useEsModules()

        browser {
            commonWebpackConfig {
                outputFileName = "fencing-web.js"
            }
        }
        binaries.executable()
    }

    sourceSets {
        val wasmJsMain by getting {
            // The generated BuildInfo. Passing the task rather than the
            // directory it writes to is what tells Gradle to run it before
            // the compilation that reads it.
            kotlin.srcDir(generateWebBuildInfo)

            dependencies {
                implementation(project(":shared"))

                // The shared Compose user interface. Today the page uses it
                // only for the theme; the screens follow.
                implementation(project(":ui"))
                implementation(compose.runtime)
                implementation(compose.foundation)
                implementation(compose.material3)
                implementation(compose.ui)
            }
        }
    }
}
